### Analyzing  Data

In [1]:
#Libraries
from pandas import read_csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import matplotlib as matplotlib
import matplotlib.lines as mlines
import sklearn

In [2]:
url = "dataset.csv"
dataset = read_csv(url)
dataset = dataset.iloc[: , :2]
dataset.dropna()
dataset.head(5)

Review Sentiment
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive
1                                          sahi bt h  Positive
2                                        Kya bt hai,  Positive
3                                         Wah je wah  Positive
4                               Are wha kaya bat hai  Positive

In [3]:
print("Number of data points: ",dataset.size)
print(dataset.groupby('Sentiment').size())

Number of data points:  40458
Sentiment
Negative    5287
Neutral     8929
Positive    6013
dtype: int64


## Creating TF-IDF Vectors

In [4]:
reviews = list(dataset.Review.astype('U'))
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=800, ngram_range = (2,2))
X = vectorizer.fit_transform(reviews).toarray()
print(vectorizer.get_feature_names())
print(X)


['aaj bhi', 'aap ka', 'aap ke', 'aap ki', 'aap ko', 'aap ne', 'aata hai', 'ab tak', 'ab to', 'abdul haq', 'abdullah haroon', 'abhi tak', 'abid ali', 'acha hai', 'acha laga', 'achi hai', 'achi quality', 'adnan ansar', 'aik aur', 'aik bar', 'aik din', 'aik saal', 'aisa hi', 'aj kal', 'akram shaheed', 'ali bhutto', 'ali khan', 'all india', 'allah aap', 'allah allah', 'allah ap', 'allah apko', 'allah in', 'allah ka', 'allah ki', 'allah pak', 'altaf hussain', 'ameen ameen', 'ansar gujjar', 'anti ko', 'ap ka', 'ap ki', 'ap ko', 'ap logo', 'ap ne', 'ap ny', 'ap se', 'apne career', 'apni zindagi', 'app ko', 'app nay', 'assembly ke', 'ata hai', 'ata kary', 'attaullah esakhelvi', 'aunty ka', 'aunty ko', 'aur aik', 'aur apne', 'aur apni', 'aur in', 'aur is', 'aur isi', 'aur na', 'aur pakistan', 'aur phir', 'aur un', 'aur us', 'aur wo', 'aur ye', 'awam ka', 'awam ko', 'ayub khan', 'azam khan', 'baat hai', 'baat nahi', 'bachon ko', 'bad mein', 'bad wo', 'badshah salamat', 'bal ke', 'bana kar', 'bar

## Creating Train Test Split

In [5]:
y = dataset.iloc[:, 1] # input labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### ML Models for Classification

In [6]:
def run_algorithm(classifier, X_train, X_test, y_train, y_test):
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    # Evaluation Metrix 
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    accuracy_N = accuracy_score(y_test, y_pred)

    print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred),"\n")

    print("The accuracy score: ",accuracy_N*100)
    f1_score_N = f1_score(y_test, y_pred, average = 'weighted')
    print("F1 Score: ", f1_score_N*100)
    precision = precision_score(y_test, y_pred, average='weighted')
    print("The Precision Score: ", precision*100)
    recall = recall_score(y_test, y_pred, average='weighted')
    print("The Recall Score: ", recall*100)
    

In [7]:
# using Naive Bayes
from sklearn.naive_bayes import GaussianNB
print("->Naive Bayes with BOW Vectors Bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = GaussianNB()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Naive Bayes with BOW Vectors Bi-gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 952   53   67]
 [1467  187  128]
 [ 834   89  269]] 

The accuracy score:  34.799802273850716
F1 Score:  29.038454887798487
The Precision Score:  49.86764637112
The Recall Score:  34.799802273850716


In [8]:
# using Random Forest
from sklearn.ensemble import RandomForestClassifier
print("->Random Forest with BOW Vectors Bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = RandomForestClassifier()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Random Forest with BOW Vectors Bi-gram and top 800 features

20% Testing Data | 80% Training Data


C:\Users\jumsh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Confusion Matrix:
 [[ 192  742  138]
 [ 129 1456  197]
 [ 125  697  370]] 

The accuracy score:  49.87642115669797
F1 Score:  45.61729886440326
The Precision Score:  49.019020417011106
The Recall Score:  49.87642115669797


In [9]:
# using Adboost
from sklearn.ensemble import AdaBoostClassifier
print("->Adboost with BOW Vectors Bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Adboost with BOW Vectors Bi-gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 206  751  115]
 [ 138 1458  186]
 [ 144  685  363]] 

The accuracy score:  50.09886307464162
F1 Score:  45.98759448598803
The Precision Score:  49.47969640861196
The Recall Score:  50.09886307464162


In [10]:
#Using KNN
from sklearn.neighbors import KNeighborsClassifier
print("->KNN with BOW Vectors Bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf =  KNeighborsClassifier(n_neighbors=3)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->KNN with BOW Vectors Bi-gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 208  736  128]
 [ 131 1459  192]
 [ 139  685  368]] 

The accuracy score:  50.29658922392486
F1 Score:  46.212081173143574
The Precision Score:  49.599966208515475
The Recall Score:  50.29658922392486
