### Analyzing  Data

In [1]:
#Libraries
from pandas import read_csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import matplotlib as matplotlib
import matplotlib.lines as mlines
import sklearn

In [2]:
url = "dataset.csv"
dataset = read_csv(url)
dataset = dataset.iloc[: , :2]
dataset.dropna()
dataset.head(5)

Review Sentiment
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive
1                                          sahi bt h  Positive
2                                        Kya bt hai,  Positive
3                                         Wah je wah  Positive
4                               Are wha kaya bat hai  Positive

In [3]:
print("Number of data points: ",dataset.size)
print(dataset.groupby('Sentiment').size())

Number of data points:  40458
Sentiment
Negative    5287
Neutral     8929
Positive    6013
dtype: int64


## Creating TF-IDF Vectors

In [4]:
reviews = list(dataset.Review.astype('U'))
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=800)
X = vectorizer.fit_transform(reviews).toarray()
print(vectorizer.get_feature_names())
print(X)


['10', '11', '12', '14', '15', '20', '50', '70', 'aa', 'aaj', 'aala', 'aam', 'aap', 'aata', 'aaya', 'ab', 'abdul', 'abdullah', 'abhi', 'abi', 'acha', 'achi', 'acting', 'ada', 'afia', 'afrad', 'afridi', 'agar', 'agr', 'ahmed', 'aik', 'aisa', 'aise', 'aisi', 'aj', 'akram', 'alam', 'ali', 'all', 'allah', 'almi', 'altaf', 'amal', 'ameen', 'america', 'and', 'anwar', 'ap', 'apka', 'apki', 'apko', 'apna', 'apnay', 'apne', 'apni', 'apny', 'app', 'are', 'army', 'arsal', 'as', 'asar', 'assembly', 'ata', 'august', 'aunty', 'aur', 'aurat', 'awam', 'award', 'awaz', 'ay', 'aya', 'aye', 'azam', 'azeem', 'ba', 'baad', 'baar', 'baat', 'bacha', 'bachi', 'bachon', 'bad', 'bal', 'balke', 'ban', 'bana', 'banane', 'banaya', 'band', 'bano', 'bar', 'bara', 'baras', 'bare', 'bari', 'bas', 'bat', 'bata', 'be', 'behtar', 'behtareen', 'benazir', 'beshak', 'best', 'beta', 'beti', 'bhai', 'bhar', 'bharat', 'bharti', 'bhe', 'bhee', 'bhi', 'bhot', 'bht', 'bhutto', 'bi', 'bilkul', 'bohat', 'bohot', 'boht', 'bol', 'bri

## Creating Train Test Split

In [5]:
y = dataset.iloc[:, 1] # input labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### ML Models for Classification

In [6]:
def run_algorithm(classifier, X_train, X_test, y_train, y_test):
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    # Evaluation Metrix 
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    accuracy_N = accuracy_score(y_test, y_pred)

    print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred),"\n")

    print("The accuracy score: ",accuracy_N*100)
    f1_score_N = f1_score(y_test, y_pred, average = 'weighted')
    print("F1 Score: ", f1_score_N*100)
    precision = precision_score(y_test, y_pred, average='weighted')
    print("The Precision Score: ", precision*100)
    recall = recall_score(y_test, y_pred, average='weighted')
    print("The Recall Score: ", recall*100)
    

In [7]:
# using Naive Bayes
from sklearn.naive_bayes import GaussianNB
print("->Naive Bayes with BOW Vectors and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = GaussianNB()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Naive Bayes with BOW Vectors and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 464  474  144]
 [ 292 1314  224]
 [ 205  413  516]] 

The accuracy score:  56.69797330696985
F1 Score:  55.96810649912809
The Precision Score:  56.2744086188237
The Recall Score:  56.69797330696985


In [8]:
# using Random Forest
from sklearn.ensemble import RandomForestClassifier
print("->Random Forest with BOW Vectors and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = RandomForestClassifier()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Random Forest with BOW Vectors and top 800 features

20% Testing Data | 80% Training Data


C:\Users\jumsh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Confusion Matrix:
 [[ 456  413  213]
 [ 322 1232  276]
 [ 187  351  596]] 

The accuracy score:  56.45081562036579
F1 Score:  56.09913929824572
The Precision Score:  55.95012985221689
The Recall Score:  56.45081562036579


In [9]:
# using Adboost
from sklearn.ensemble import AdaBoostClassifier
print("->Adboost with BOW Vectors and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Adboost with BOW Vectors and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 475  403  204]
 [ 320 1232  278]
 [ 203  347  584]] 

The accuracy score:  56.62382600098863
F1 Score:  56.32992418594524
The Precision Score:  56.197501288983595
The Recall Score:  56.62382600098863


In [10]:
#Using KNN
from sklearn.neighbors import KNeighborsClassifier
print("->KNN with BOW Vectors and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf =  KNeighborsClassifier(n_neighbors=3)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->KNN with BOW Vectors and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 470  412  200]
 [ 353 1186  291]
 [ 191  354  589]] 

The accuracy score:  55.48690064260998
F1 Score:  55.273254590841844
The Precision Score:  55.16173350648997
The Recall Score:  55.48690064260998


###### 