### Analyzing  Data

In [1]:
#Libraries
from pandas import read_csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
import matplotlib as matplotlib
import matplotlib.lines as mlines
import sklearn

In [2]:
url = "dataset.csv"
dataset = read_csv(url)
dataset = dataset.iloc[: , :2]
dataset.dropna()
dataset.head(5)

Review Sentiment
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive
1                                          sahi bt h  Positive
2                                        Kya bt hai,  Positive
3                                         Wah je wah  Positive
4                               Are wha kaya bat hai  Positive

In [3]:
print("Number of data points: ",dataset.size)
print(dataset.groupby('Sentiment').size())

Number of data points:  40458
Sentiment
Negative    5287
Neutral     8929
Positive    6013
dtype: int64


## Creating TF-IDF Vectors

In [4]:
reviews = list(dataset.Review.astype('U'))
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, ngram_range = (2,2))
X = vectorizer.fit_transform(reviews).toarray()
print(vectorizer.get_feature_names())
print(X)


['10 saal', '11 baje', '14 august', '14 saal', '16 august', '1936 mein', '1937 mein', '1938 mein', '1940 mein', '1942 mein', '1944 mein', '1946 ko', '1946 mein', '1947 mein', '1948 mein', '1949 mein', '1950 mein', '1951 mein', '1952 ko', '1952 mein', '1953 mein', '1954 mein', '1955 mein', '1956 mein', '1957 mein', '1958 mein', '1959 mein', '1960 mein', '1961 mein', '1962 mein', '1963 mein', '1964 mein', '1965 ki', '1965 mein', '1966 mein', '1967 mein', '1968 mein', '1969 mein', '1970 mein', '1971 ko', '1971 mein', '1972 mein', '1973 mein', '1974 mein', '1975 ko', '1976 mein', '1977 mein', '1978 mein', '1979 mein', '1980 mein', '1981 mein', '1982 mein', '1983 mein', '1984 mein', '1985 mein', '1986 mein', '1988 mein', '1989 mein', '1990 ko', '1990 mein', '1991 mein', '1992 mein', '1993 ko', '1993 mein', '1994 ko', '1994 mein', '1995 mein', '1996 ko', '1997 ko', '1997 mein', '1998 mein', '1999 mein', '20 saal', '2001 mein', '2002 mein', '2004 ko', '2004 mein', '2005 ko', '2005 mein', '200

## Creating Train Test Split

In [5]:
y = dataset.iloc[:, 1] # input labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### ML Models for Classification

In [6]:
def run_algorithm(classifier, X_train, X_test, y_train, y_test):
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    # Evaluation Metrix 
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import precision_score
    from sklearn.metrics import recall_score
    accuracy_N = accuracy_score(y_test, y_pred)

    print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred),"\n")

    print("The accuracy score: ",accuracy_N*100)
    f1_score_N = f1_score(y_test, y_pred, average = 'weighted')
    print("F1 Score: ", f1_score_N*100)
    precision = precision_score(y_test, y_pred, average='weighted')
    print("The Precision Score: ", precision*100)
    recall = recall_score(y_test, y_pred, average='weighted')
    print("The Recall Score: ", recall*100)
    

In [7]:
# using Naive Bayes
from sklearn.naive_bayes import GaussianNB
print("->Naive Bayes with TF-IDF Vectors using Bi-Gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = GaussianNB()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Naive Bayes with TF-IDF Vectors using Bi-Gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 861  127   95]
 [1202  398  180]
 [ 544  199  440]] 

The accuracy score:  41.99209095402867
F1 Score:  40.033114089281845
The Precision Score:  51.01791713071424
The Recall Score:  41.99209095402867


In [8]:
# using Random Forest
from sklearn.ensemble import RandomForestClassifier
print("->Random Forest with TF-IDF Vectors bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
classifier = RandomForestClassifier()
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Random Forest with TF-IDF Vectors bi-gram and top 800 features

20% Testing Data | 80% Training Data


C:\Users\jumsh\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Confusion Matrix:
 [[ 304  646  133]
 [ 183 1387  210]
 [ 166  571  446]] 

The accuracy score:  52.817597627286204
F1 Score:  50.43781060713333
The Precision Score:  52.422245416869785
The Recall Score:  52.817597627286204


In [9]:
# using Adboost
from sklearn.ensemble import AdaBoostClassifier
print("->Adboost with TF-IDF Vectors bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf = AdaBoostClassifier(n_estimators=100, random_state=0)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->Adboost with TF-IDF Vectors bi-gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 306  634  143]
 [ 185 1381  214]
 [ 142  583  458]] 

The accuracy score:  53.01532377656946
F1 Score:  50.70614196781364
The Precision Score:  52.75629454338699
The Recall Score:  53.01532377656946


In [10]:
#Using KNN
from sklearn.neighbors import KNeighborsClassifier
print("->KNN with TF-IDF Vectors bi-gram and top 800 features\n")
print("20% Testing Data | 80% Training Data")
clf =  KNeighborsClassifier(n_neighbors=3)
run_algorithm(classifier, X_train, X_test, y_train, y_test)

->KNN with TF-IDF Vectors bi-gram and top 800 features

20% Testing Data | 80% Training Data
Confusion Matrix:
 [[ 295  646  142]
 [ 183 1388  209]
 [ 142  556  485]] 

The accuracy score:  53.583786455758776
F1 Score:  51.26757029307713
The Precision Score:  53.27541407870173
The Recall Score:  53.583786455758776
